name: pre-commit

on:
  workflow_call:
    inputs:
      asdf:
        default: false
        description: Install asdf and plugins if true
        required: false
        type: boolean
      python-version:
        default: '3.8'
        description: Python runtime version
        required: false
        type: string
    secrets:
      ssh-key:
        description: Machine user GitHub SSH key
        required: false

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    name: Check all files with pre-commit
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Install asdf
        uses: asdf-vm/actions/setup@v1
        if: inputs.asdf
      - name: Install asdf plugins
        if: inputs.asdf
        run: make asdf
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install machine user SSH key
        env:
          SSH_KEY: ${{ secrets.ssh-key }}
        if: env.SSH_KEY != null
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: |
            ${{ secrets.ssh-key }}
      - uses: pre-commit/action@v2.0.3
        env:
          SKIP: no-commit-to-branch
