name: pre-commit

on:
  workflow_call:
    inputs:
      asdf:
        default: false
        description: Install asdf and plugins if true
        required: false
        type: boolean
      node-version:
        default: '18.16.0'
        description: Node runtime version
        required: false
        type: string
      python-version:
        default: '3.10'
        description: Python runtime version
        required: false
        type: string
    secrets:
      ssh-key:
        description: Machine user GitHub SSH key
        required: false

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    name: Check all files with pre-commit
    timeout-minutes: 5
    steps:
      - name: Set up Node ${{ inputs.node-version }}
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ inputs.node-version }}
      - uses: actions/setup-python@v4.6.0
        with:
          python-version: ${{ inputs.python-version }}
      - uses: actions/checkout@v3.5.2
      - name: Install asdf
        uses: asdf-vm/actions/setup@v2.1.0
        if: inputs.asdf
      - name: Install asdf plugins
        if: inputs.asdf
        run: make asdf
      - name: Install machine user SSH key
        env:
          SSH_KEY: ${{ secrets.ssh-key }}
        if: env.SSH_KEY != null
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: |
            ${{ secrets.ssh-key }}
      - uses: pre-commit/action@v3.0.0
        env:
          SKIP: no-commit-to-branch
